name: ${project.parent.name}
version: ${project.parent.version}
main: de.fof1092.almostflatlandsreloaded.Main
author: F_o_F_1092
load: startup
commands:
  almostflatlandsreloaded:
    description: none
    usage: /AlmostFlatLandsReloaded
    aliases: [aflr]