name: AlmostFlatLandsReloaded
main: de.fof1092.almostflatlandsreloaded.AlmostFlatlandsReloaded
version: ${project.parent.version}
api-version: 1.13
author: F_o_F_1092
load: startup
commands:
  almostflatlandsreloaded:
    description: none
    usage: /AlmostFlatLandsReloaded
    aliases: [aflr]