name: Build AlmostFlatLandsReloaded

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: mvn -V -B clean install --file pom.xml

      - name: Upload Plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: AlmostFlatLandsReloaded-JAR
          path: dist/target/*.jar
          if-no-files-found: error
